In [4]:
import pandas as pd

data = {
    "Age": [22, None, 25, None, 35],
    "City": ["Delhi", None, "Mumbai", None, "Chennai"],
    "porfit": [500, 600, None, None, 750]
}

df = pd.DataFrame(data)
print(df)

    Age     City  porfit
0  22.0    Delhi   500.0
1   NaN     None   600.0
2  25.0   Mumbai     NaN
3   NaN     None     NaN
4  35.0  Chennai   750.0

In [5]:
print(df.fillna(0))

    Age     City  porfit
0  22.0    Delhi   500.0
1   0.0        0   600.0
2  25.0   Mumbai     0.0
3   0.0        0     0.0
4  35.0  Chennai   750.0

In [6]:
print(df["Age"].fillna(df["Age"].mean()))

0    22.000000
1    27.333333
2    25.000000
3    27.333333
4    35.000000
Name: Age, dtype: float64

In [7]:
print(df["Age"].fillna(df["Age"].median()))

0    22.0
1    25.0
2    25.0
3    25.0
4    35.0
Name: Age, dtype: float64

In [8]:
print(df["City"].fillna(df["City"].mode()[0]))

0      Delhi
1    Chennai
2     Mumbai
3    Chennai
4    Chennai
Name: City, dtype: object

In [9]:
df.fillna(method='ffill')

<ipython-input-9-5c0beae7dc1e>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

    Age     City  porfit
0  22.0    Delhi   500.0
1  22.0    Delhi   600.0
2  25.0   Mumbai   600.0
3  25.0   Mumbai   600.0
4  35.0  Chennai   750.0

In [10]:
df.fillna(method='bfill')

<ipython-input-10-b823574c06e2>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

    Age     City  porfit
0  22.0    Delhi   500.0
1  25.0   Mumbai   600.0
2  25.0   Mumbai   750.0
3  35.0  Chennai   750.0
4  35.0  Chennai   750.0

In [11]:
print(df.fillna(0, inplace=True))

None

In [12]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Marks": [50, np.nan, np.nan, 70, np.nan, np.nan, 90],
    "City": ["Delhi", "Mumbai", np.nan, np.nan, "Chennai", np.nan, np.nan]
})

print("Original DataFrame:")
print(df)

df.fillna(method="ffill", limit=1)

Original DataFrame:
   Marks     City
0   50.0    Delhi
1    NaN   Mumbai
2    NaN      NaN
3   70.0      NaN
4    NaN  Chennai
5    NaN      NaN
6   90.0      NaN

<ipython-input-12-2428e6a92d27>:12: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", limit=1)

   Marks     City
0   50.0    Delhi
1   50.0   Mumbai
2    NaN   Mumbai
3   70.0      NaN
4   70.0  Chennai
5    NaN  Chennai
6   90.0      NaN